application: stanfordkarel
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /images
  static_dir: images

- url: /codeMirror
  static_dir: codeMirror

- url: /lib
  static_dir: lib

- url: /worlds
  static_dir: worlds

- url: .*
  script: main.py

builtins:
- datastore_admin: on
